### PR TITLE
1.11.x nl

### PR DESCRIPTION
**Pull request by spacecabbie**
admin / admin-gids checked.

Note: Gitlocalize machine translation script has done a incredible translation I am hard pressed to vind issues. I had several people have a look all we can find are in general smalish in error and debatable if it should be changed.
example would be: The teacher should first login to the system VS The teacher has to login to the system first

### CODE REVIEW

**Comment by ywarnier** [comment]
How did you manage to use GitLocalize with the branch structure?

**Comment by spacecabbie** [comment]
Oh you saw that eh. Was playing with that as little surprise since i know you wanted to get that to work.
https://i.imgur.com/cor6O7W.png
This is what i did although unfortunately this does not work for existing repo/branches it will simply not detect existing files

**Comment by ywarnier** [comment]
I guess one could always hack a little bit into it and create a repo with two folders for the time of the translation. I didn't know GitLocalize had a machine translator.

**Comment by spacecabbie** [comment]
> I guess one could always hack a little bit into it and create a repo with two folders for the time of the translation. I didn't know GitLocalize had a machine translator.

That's what i did now created a new repo and only have en and nl in there works good.
How did you translate the rest if the files then ?

**Comment by ywarnier** [comment]
One by one with Google Translate. Did a reasonnable job and was reasonnably fast (plus very low technical requirements) in combination with online edition on Github.

**Pull request merged**
