### PR TITLE
Deleted the other merge this one is better.

### PR DESCRIPTION
**Pull request by spacecabbie**
All translations admin/dev checked.
fixed layout issues for gitlocalize (damn that software is annoyingly picky.... need a lot of improvement imho, still the easy of editing and quality of the translation beats anything i have seen.

### CODE REVIEW

**Comment by ywarnier** [comment]
Style-wise, I'm not sure you *can* actually remove the "\" in front of "(" or ")" characters in Markdown syntax and still have the same result (same thing for the "*" characters like in "1.11.\*"), but I'm happy to try and see what happens. I assume those were there for a reason.

**Comment by spacecabbie** [comment]
> Style-wise, I'm not sure you _can_ actually remove the "" in front of "(" or ")" characters in Markdown syntax and still have the same result (same thing for the "*" characters like in "1.11.*"), but I'm happy to try and see what happens. I assume those were there for a reason.

Yea gitlocalize has a hard time with it if this is due to the fact we machine translated elsewhere. I am not sure.
But it seems to prefer to have a source language and then create the files them zelf then detecting whats already done.

**Comment by spacecabbie** [comment]
image
Conflicts are nothing more then layout issues. so there are still some to come.

**Comment by ywarnier** [comment]
Thanks. Merged.

**Pull request merged**
